[package]
name = "plectrum"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "An easy way to represent lookup tables in a db as rust enums"
readme = "../README.md"
repository = "https://github.com/naiquevin/plectrum"
keywords = ["lookup-table", "enum"]
categories = ["rust-patterns"]

[dependencies]
bimap = "0.6.3"
plectrum-derive = { version = "0.2.0", path = "../plectrum-derive", optional = true }
sqlx = { version = "0.8.6", optional = true }
thiserror = "2.0.16"

[dev-dependencies]
tokio = { version = "1.47.1", features = ["full"] }

[features]
derive = ["dep:plectrum-derive"]
sqlx = ["dep:sqlx"]
